console.log;
console.log.bind;
console.warn;
console.warn.bind;
console.error;
console.error.bind;
console.group;
console.group.bind;
console.groupEnd;
console.groupEnd.bind;
var encodeURIComponent;
var decodeURIComponent;
Object.Fragment;
Object.index;
Object.exec;
Object.findDOMNode;
Object.Children;
Object.Children.toArray;
Object.render;
Object.out;
Object.out.println;
Object.createElement;
Object.createElement.apply;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
var SyntaxError;
var URIError;
TypeError.prototype.toString;
var process;
process.hrtime;
var require;
require.resolve;
var RangeError;
var setTimeout;
RegExp.prototype.bidi$bidi$PatternSegment$;
RegExp.prototype.bidi$bidi$PatternSegment$segment_regex_group$arity$1;
RegExp.prototype.pattern;
RegExp.prototype.bidi$bidi$Pattern$match_pattern$arity$2;
RegExp.prototype.bidi$bidi$PatternSegment$matches_QMARK_$arity$2;
RegExp.prototype.bidi$bidi$Pattern$unmatch_pattern$arity$2;
RegExp.prototype.bidi$bidi$PatternSegment$param_key$arity$1;
RegExp.prototype.bidi$bidi$PatternSegment$transform_param$arity$1;
RegExp.prototype.bidi$bidi$Pattern$;
var Java;
Java.type;
var EvalError;
